import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
import { info, success, warn, error, spinner, table, log } from "./index.js";
import {
  getProfilePath,
  isFirstRun as isFirstRunProfile,
  loadProfileOrDefault,
  runOnboarding,
} from "./onboarding.js";
import { buildAgentPrompts } from "../shared/profile.js";
import type { HivemindProfile } from "../shared/profile.js";

// ── Prompt helper ─────────────────────────────────────────────────────────────

async function prompt(question: string, defaultValue?: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const suffix = defaultValue ? ` (${defaultValue})` : "";

  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

// ── init ──────────────────────────────────────────────────────────────────────

interface InitOptions {
  yes?: boolean;
  template?: string;
}

export async function initCommand(options: InitOptions): Promise<void> {
  const cwd = process.cwd();

  if (fs.existsSync(path.join(cwd, "hivemind.yaml"))) {
    warn("A hivemind.yaml already exists in this directory.");
    const overwrite = await prompt("Overwrite? (y/N)", "N");
    if (overwrite.toLowerCase() !== "y") {
      info("Init cancelled.");
      return;
    }
  }

  let projectName = path.basename(cwd);
  let primaryModel = "anthropic/claude-sonnet-4-20250514";
  let enableDashboard = true;
  let dashboardPort = 3000;

  if (!options.yes) {
    projectName = await prompt("Project name", projectName);
    primaryModel = await prompt("Primary LLM model", primaryModel);
    const dashAnswer = await prompt("Enable web dashboard?", "yes");
    enableDashboard = ["yes", "y", "true"].includes(dashAnswer.toLowerCase());
    if (enableDashboard) {
      const portAnswer = await prompt("Dashboard port", "3000");
      dashboardPort = parseInt(portAnswer, 10) || 3000;
    }
  }

  const s = spinner("Scaffolding project...");

  const configContent = `# HIVEMIND Configuration
# Generated by \`hivemind init\`

name: "${projectName}"
version: "1.0.0"

llm:
  primary:
    provider: anthropic
    model: "${primaryModel}"
    maxTokens: 16000
  fallback:
    provider: ollama
    model: llama3.2
    maxTokens: 16000

agents:
  coordinator:
    role: coordinator
    description: "Orchestrates tasks across the swarm"
    model: \${llm.primary}
    skills:
      - task-planning
      - delegation

  researcher:
    role: researcher
    description: "Gathers and synthesizes information"
    model: \${llm.primary}
    skills:
      - web-search
      - summarization

skills: []

connectors: []

dashboard:
  enabled: ${enableDashboard}
  port: ${dashboardPort}

storage:
  type: sqlite
  path: ./data/hivemind.db
`;

  fs.mkdirSync(path.join(cwd, "data"), { recursive: true });
  fs.mkdirSync(path.join(cwd, "skills"), { recursive: true });
  fs.mkdirSync(path.join(cwd, "agents"), { recursive: true });
  fs.writeFileSync(path.join(cwd, "hivemind.yaml"), configContent, "utf-8");

  if (!fs.existsSync(path.join(cwd, ".env"))) {
    fs.writeFileSync(
      path.join(cwd, ".env"),
      "# HIVEMIND Environment Variables\n# ANTHROPIC_API_KEY=\n# OPENAI_API_KEY=\n",
      "utf-8",
    );
  }

  s.succeed("Project initialized successfully");
  log("");
  info(`Config written to ${path.join(cwd, "hivemind.yaml")}`);
  info("Next steps:");
  log("  1. Set your API keys in .env");
  log('  2. Run "hivemind up" to start the swarm');
  log("");
}

// ── up ────────────────────────────────────────────────────────────────────────

interface UpOptions {
  detach?: boolean;
  config?: string;
  dashboard?: boolean;
}

// Global state shared between up and task commands
let swarmState: {
  llm: import("../core/llm.js").LLMAdapter | null;
  agents: Map<string, import("../agents/llm-agent.js").LLMAgent>;
  bus: import("events").EventEmitter;
  dashboardAgents: Map<string, any>;
  memoryStore?: import("../memory/store.js").MemoryStore;
  metricsTracker?: import("../core/agent-metrics.js").MetricsTracker;
  skillRegistry?: import("../skills/registry.js").SkillRegistry;
  refreshPrompts?: (newProfile: import("../shared/profile.js").HivemindProfile) => void;
} | null = null;

export function getSwarmState() {
  return swarmState;
}

export async function upCommand(options: UpOptions): Promise<void> {
  const profilePath = getProfilePath();
  if (isFirstRunProfile(profilePath) && process.stdin.isTTY) {
    await runOnboarding({
      cwd: process.cwd(),
      profilePath,
      configPath: path.resolve(options.config ?? "hivemind.yaml"),
    });
  }

  // ── Load env files ──────────────────────────────────────────────────────────
  const homeDir = process.env["HOME"] ?? "/Users/" + (process.env["USER"] ?? "user");

  // Load env vars from a KEY=value file (skip comments, source lines, empty lines)
  function loadEnvFile(filePath: string) {
    if (!fs.existsSync(filePath)) return;
    const envLines = fs.readFileSync(filePath, "utf-8").split("\n");
    for (const line of envLines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("source")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      let val = trimmed.slice(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      if (!process.env[key]) {
        process.env[key] = val;
      }
    }
  }

  // Load shared env keys (ai.env has GOOGLE_API_KEY, ANTHROPIC_API_KEY, etc.)
  loadEnvFile(path.join(homeDir, ".config", "shared-env", "ai.env"));
  // Load global HIVEMIND env
  loadEnvFile(path.join(homeDir, ".hivemind", ".env"));
  // Load project-local env
  loadEnvFile(path.resolve(".env"));

  const profile = loadProfileOrDefault(profilePath);
  const userName = profile.user.name;
  const cofounderName = profile.cofounder.name;
  const cofounderPersonality = profile.cofounder.personalityPrompt;
  const agentNames = {
    nova: profile.agents["nova-1"].name,
    scout: profile.agents["scout-1"].name,
    builder: profile.agents["builder-1"].name,
    sentinel: profile.agents["sentinel-1"].name,
    oracle: profile.agents["oracle-1"].name,
    courier: profile.agents["courier-1"].name,
  };

  const configPath = path.resolve(options.config ?? "hivemind.yaml");

  if (!fs.existsSync(configPath)) {
    error(`Config file not found: ${configPath}`);
    error('Run "hivemind init" first to create a configuration.');
    process.exit(1);
  }

  const s = spinner("Starting HIVEMIND swarm...");

  // Load configuration
  s.update("Loading configuration...");
  const configRaw = fs.readFileSync(configPath, "utf-8");

  // Parse YAML config for connectors and security sections
  let parsedConfig: Record<string, unknown> = {};
  try {
    const { parse: parseYaml } = await import("yaml");
    parsedConfig = (parseYaml(configRaw) ?? {}) as Record<string, unknown>;
  } catch {
    // YAML parse failure is non-fatal — connectors just won't load
  }

  // Load owner IDs into trust gate so connector messages can be classified
  try {
    const { trustGate } = await import("../core/trust.js");
    const security = parsedConfig["security"] as Record<string, unknown> | undefined;
    const ownerIds = security?.["ownerIds"];
    if (ownerIds && typeof ownerIds === "object" && !Array.isArray(ownerIds)) {
      trustGate.loadOwnerIds(ownerIds as Record<string, string[]>);
    }
  } catch { /* non-critical */ }

  // ── Step 1: Detect all available LLM providers ────────────────────────────
  s.update("Detecting LLM providers...");

  const availableProviders: string[] = [];
  let proxyServer: import("http").Server | null = null;

  // Check direct API keys first
  if (process.env["ANTHROPIC_API_KEY"]) {
    availableProviders.push("anthropic");
  }
  if (process.env["OPENAI_API_KEY"]) {
    availableProviders.push("openai");
  }
  if (process.env["GOOGLE_API_KEY"]) {
    availableProviders.push("google");
  }

  // Try Claude Code CLI directly (uses your Max subscription, can write files)
  if (!availableProviders.includes("anthropic")) {
    try {
      const { verifyClaudeCode } = await import("../core/claude-code-provider.js");
      const claudeCheck = await verifyClaudeCode();
      if (claudeCheck.ok) {
        availableProviders.push("claude-code");
      }
    } catch {
      // Claude Code CLI not available
    }
  }

  // Try OpenAI Codex CLI (uses ChatGPT Pro/Plus subscription)
  try {
    const { verifyCodex } = await import("../core/codex-provider.js");
    const codexCheck = await verifyCodex();
    if (codexCheck.ok) {
      availableProviders.push("codex");
    }
  } catch {
    // Codex CLI not available
  }

  // Try Ollama
  try {
    const res = await fetch("http://localhost:11434/api/tags", { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      availableProviders.push("ollama");
    }
  } catch {
    // Ollama not running
  }

  // ── Step 1b: Create LLM adapters ──────────────────────────────────────────
  s.update("Connecting to LLM providers...");

  const { LLMAdapter } = await import("../core/llm.js");

  // Primary adapter — used for research/analysis agents (prefers Claude)
  let primaryLlm: InstanceType<typeof LLMAdapter> | null = null;
  // Code adapter — used for code-focused agents (prefers Codex)
  let codeLlm: InstanceType<typeof LLMAdapter> | null = null;

  const hasClaude = availableProviders.includes("anthropic") || availableProviders.includes("claude-code");
  const hasCodex = availableProviders.includes("codex");
  const hasOpenAI = availableProviders.includes("openai");
  const hasGoogle = availableProviders.includes("google");
  const hasOllama = availableProviders.includes("ollama");

  // Build primary LLM (Claude-first, then Google/Gemini, then OpenAI, then Ollama)
  if (hasClaude || hasGoogle || hasOpenAI || hasOllama) {
    const llmConfig: Record<string, any> = {};
    let defaultProv = "";

    if (availableProviders.includes("anthropic")) {
      llmConfig["anthropic"] = { apiKey: process.env["ANTHROPIC_API_KEY"] };
      defaultProv = "anthropic";
    } else if (availableProviders.includes("claude-code")) {
      defaultProv = "claude-code";
    } else if (hasGoogle) {
      llmConfig["google"] = { apiKey: process.env["GOOGLE_API_KEY"] };
      defaultProv = "google";
    } else if (hasOpenAI) {
      llmConfig["openai"] = { apiKey: process.env["OPENAI_API_KEY"] };
      defaultProv = "openai";
    } else if (hasOllama) {
      llmConfig["ollama"] = { baseUrl: "http://localhost:11434" };
      defaultProv = "ollama";
    }

    // Note: Google/Gemini is detected but NOT added to the general chat fallback chain.
    // Gemini is reserved for image generation (Imagen) and document extraction only.

    primaryLlm = new LLMAdapter({
      providers: llmConfig,
      defaultProvider: defaultProv,
      fallbackChain: [defaultProv],
    });

    // Register Claude Code as a custom provider (subprocess-based, can write files)
    if (availableProviders.includes("claude-code")) {
      const { ClaudeCodeProvider } = await import("../core/claude-code-provider.js");
      primaryLlm.registerProvider("claude-code", new ClaudeCodeProvider());
    }
  }

  // Build code LLM (Codex-first, falls back to primary)
  if (hasCodex) {
    codeLlm = new LLMAdapter({
      providers: {},
      defaultProvider: "codex",
      fallbackChain: ["codex"],
    });
    const { CodexProvider } = await import("../core/codex-provider.js");
    codeLlm.registerProvider("codex", new CodexProvider());
  }

  // If only one provider exists, both adapters point to it
  if (!primaryLlm && codeLlm) primaryLlm = codeLlm;
  if (!codeLlm && primaryLlm) codeLlm = primaryLlm;

  // Determine display label
  const llmProvider = availableProviders.length > 0 ? availableProviders[0] : "none";
  const tandemMode = hasClaude && hasCodex;

  // ── Step 1c: Initialize persistent memory store ─────────────────────────
  s.update("Initializing memory store...");

  const { MemoryStore } = await import("../memory/store.js");
  const dataDir = path.resolve("data");
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
  const memoryStore = new MemoryStore({ dbPath: path.join(dataDir, "hivemind.db"), embeddingDimension: 384 });

  // Try to load local embedder for semantic search (optional — gracefully falls back)
  let embedder: import("../memory/store.js").EmbeddingProvider | undefined;
  try {
    const { tryCreateLocalEmbedder } = await import("../memory/local-embedder.js");
    embedder = (await tryCreateLocalEmbedder()) ?? undefined;
  } catch {
    // @xenova/transformers not installed — keyword search only
  }
  await memoryStore.initialize(embedder);

  // ── Step 2: Create real LLM agents with role-based provider assignment ─────
  s.update("Spawning agents...");

  const { LLMAgent } = await import("../agents/llm-agent.js");

  // Code-focused roles get Codex (o4-mini), research/analysis roles get Claude
  const codeRoles = new Set(["builder", "sentinel"]);

  let currentPrompts = buildAgentPrompts(profile);

  const AGENT_PREAMBLE = currentPrompts.preamble;

  // AGENT_PREAMBLE and NOVA_PROMPT templates have been moved to buildAgentPrompts() in src/shared/profile.ts.
  // This allows refreshPrompts() to rebuild them when the profile changes at runtime.
  const NOVA_PROMPT = currentPrompts.nova;


  const agentConfigs = [
    { id: "nova-1", name: agentNames.nova, role: "coordinator", systemPrompt: NOVA_PROMPT },
    { id: "scout-1", name: agentNames.scout, role: "scout", systemPrompt: `${AGENT_PREAMBLE}${currentPrompts.agentSuffixes['scout-1'] || ''}` },
    { id: "builder-1", name: agentNames.builder, role: "builder", systemPrompt: `${AGENT_PREAMBLE}${currentPrompts.agentSuffixes['builder-1'] || ''}` },
    { id: "sentinel-1", name: agentNames.sentinel, role: "sentinel", systemPrompt: `${AGENT_PREAMBLE}${currentPrompts.agentSuffixes['sentinel-1'] || ''}` },
    { id: "oracle-1", name: agentNames.oracle, role: "oracle", systemPrompt: `${AGENT_PREAMBLE}${currentPrompts.agentSuffixes['oracle-1'] || ''}` },
    { id: "courier-1", name: agentNames.courier, role: "courier", systemPrompt: `${AGENT_PREAMBLE}${currentPrompts.agentSuffixes['courier-1'] || ''}` },
  ];

  const llmAgents = new Map<string, InstanceType<typeof LLMAgent>>();
  if (primaryLlm) {
    for (const cfg of agentConfigs) {
      // In tandem mode, code roles use Codex, others use Claude
      const agentLlm = codeRoles.has(cfg.role) ? (codeLlm ?? primaryLlm) : primaryLlm;
      const agent = new LLMAgent({
        identity: { id: cfg.id, name: cfg.name, role: cfg.role, version: "1.0.0" },
        llm: agentLlm,
        systemPrompt: cfg.systemPrompt,
      });
      llmAgents.set(cfg.id, agent);
    }
  }

  // Attach persistent memory store to all agents
  for (const [, agent] of llmAgents) {
    agent.attachMemoryStore(memoryStore);
  }

  // Write initial system memory entries so the dashboard has something to show
  try {
    const existing = memoryStore.listByNamespace("system");
    if (existing.length === 0) {
      await memoryStore.write({
        namespace: "system",
        title: "HIVEMIND Initialized",
        content: `Swarm started with ${llmAgents.size} agents: ${agentConfigs.map(a => a.name).join(", ")}. Providers: ${availableProviders.join(", ") || "none"}.`,
        level: 0,
        source: "system",
      });
    }
  } catch { /* non-critical */ }

  // ── Step 3: Start the dashboard ────────────────────────────────────────────
  const dashboardPort = Number(process.env["HIVEMIND_DASHBOARD_PORT"]) || 4000;

  if (options.dashboard !== false) {
    s.update("Starting dashboard...");
    const { startDashboard, bus, agents: agentMap, broadcast, setSwarmState, setConfigPath } = await import("../dashboard/server.js");

    // Initialize performance metrics tracker
    const { MetricsTracker } = await import("../core/agent-metrics.js");
    const metricsTracker = new MetricsTracker();
    for (const cfg of agentConfigs) {
      if (cfg.id !== 'nova-1') { // Don't track Nova's own metrics
        metricsTracker.register(cfg.id, cfg.name);
      }
    }

    // Register agents in dashboard
    const dashboardAgentDefs = [
      { id: "nova-1", name: agentNames.nova, type: "coordinator" as const, status: "idle" as const, skills: ["orchestrate", "delegate", "plan", "manage"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["scout-1", "builder-1", "sentinel-1", "oracle-1", "courier-1"], location: { lat: 40.7128, lng: -74.0060 } },
      { id: "scout-1", name: agentNames.scout, type: "specialist" as const, status: "idle" as const, skills: ["web-search", "summarize", "research"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["oracle-1"], location: { lat: 37.7749, lng: -122.4194 } },
      { id: "builder-1", name: agentNames.builder, type: "worker" as const, status: "idle" as const, skills: ["code-generate", "test", "deploy"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["scout-1", "sentinel-1"], location: { lat: 51.5074, lng: -0.1278 } },
      { id: "sentinel-1", name: agentNames.sentinel, type: "sentinel" as const, status: "idle" as const, skills: ["log-analyze", "anomaly-detect", "alert"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["builder-1"], location: { lat: 35.6762, lng: 139.6503 } },
      { id: "oracle-1", name: agentNames.oracle, type: "specialist" as const, status: "idle" as const, skills: ["trend-analysis", "forecast", "sentiment"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["scout-1"], location: { lat: -33.8688, lng: 151.2093 } },
      { id: "courier-1", name: agentNames.courier, type: "worker" as const, status: "idle" as const, skills: ["slack-notify", "email", "format"], memoryUsageMB: 0, uptime: 0, tasksCompleted: 0, connections: ["scout-1", "builder-1", "sentinel-1", "oracle-1"], location: { lat: 48.8566, lng: 2.3522 } },
    ];

    for (const a of dashboardAgentDefs) {
      agentMap.set(a.id, a);
    }

    startDashboard();

    // Seed swarm graph with initial agents so the visualization
    // has nodes immediately (before any tasks are submitted)
    for (const a of dashboardAgentDefs) {
      bus.emit('agent:added', a);
    }

    // Initialize skill system — load from skills/ directory with hot-reload
    const { SkillRegistry } = await import("../skills/registry.js");
    const { SkillLoader } = await import("../skills/loader.js");
    const skillRegistry = new SkillRegistry();
    const skillsDir = path.join(process.cwd(), "skills");
    const skillDirs = [skillsDir];
    const homeSkillsDir = path.join(process.env['HOME'] || '', '.hivemind', 'skills');
    if (fs.existsSync(homeSkillsDir)) {
      skillDirs.push(homeSkillsDir);
    }
    // Also scan Claude Code's skills directory (for gstack and other Claude Code skills)
    const claudeSkillsDir = path.join(process.env['HOME'] || '', '.claude', 'skills');
    if (fs.existsSync(claudeSkillsDir)) {
      skillDirs.push(claudeSkillsDir);
    }
    const skillLoader = new SkillLoader(skillRegistry, {
      skillDirs,
      watch: true, // Hot-reload on file changes
    });
    const loadedSkills = await skillLoader.loadAll();
    if (loadedSkills.length > 0) {
      console.log(`[Skills] Loaded ${loadedSkills.length} skills: ${loadedSkills.map(s => s.metadata.name).join(', ')}`);
    }

    // Save swarm state for task command and REST API
    swarmState = {
      llm: primaryLlm,
      agents: llmAgents,
      bus,
      dashboardAgents: agentMap,
      memoryStore,
      metricsTracker,
      skillRegistry,
      refreshPrompts: (newProfile: HivemindProfile) => {
        currentPrompts = buildAgentPrompts(newProfile);
        for (const [id, agent] of llmAgents) {
          (agent as any).systemPrompt = id === 'nova-1'
            ? currentPrompts.nova
            : `${currentPrompts.preamble}${currentPrompts.agentSuffixes[id] || ''}`;
        }
      },
    };
    // Inject directly into dashboard server so /api/tasks can find agents
    setSwarmState(swarmState);
    setConfigPath(configPath);

    // Wire agent events to dashboard
    for (const [agentId, agent] of llmAgents) {
      agent.on("state:change", (evt) => {
        const dashAgent = agentMap.get(agentId);
        if (dashAgent) {
          dashAgent.status = evt.to === "error" ? "error" : (evt.to === "thinking" || evt.to === "acting") ? "active" : "idle";
          dashAgent.uptime = Math.floor(process.uptime());
          bus.emit("agent:update", dashAgent);
        }
      });
    }

    // Clean up on shutdown
    const closeMemory = () => memoryStore.close();
    process.on("SIGINT", () => closeMemory());
    process.on("SIGTERM", () => closeMemory());
  }

  // ── Initialize Email Module ─────────────────────────────────────────────────
  // Email module has its own tsconfig (tsconfig.email.json) — loaded via require()
  // to avoid the main strict tsconfig from type-checking it.
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const emailMod = require("../modules/email/index.js") as {
      initEmailModule: (dir: string) => void;
      startScheduler: () => Promise<void>;
      setLLMExtractor: (fn: (systemPrompt: string, userPrompt: string) => Promise<string>) => void;
      emailBus: import("events").EventEmitter;
    };
    const dataDir = path.join(process.cwd(), "data");
    emailMod.initEmailModule(dataDir);

    // Inject the existing LLM provider for email extraction — no separate API key needed.
    // Uses the user's Claude subscription (free with Max/Pro) via Claude Code CLI.
    if (primaryLlm) {
      const extractionProvider = primaryLlm.getProvider?.("claude-code") || primaryLlm.getDefaultProvider?.();
      if (extractionProvider?.complete) {
        emailMod.setLLMExtractor(async (systemPrompt: string, userPrompt: string) => {
          const response = await extractionProvider.complete({
            messages: [
              { role: "system", content: systemPrompt },
              { role: "user", content: userPrompt },
            ],
            requestId: "email-extraction",
          });
          return typeof response.content === "string" ? response.content : "";
        });
      }
    }

    await emailMod.startScheduler();

    // Wire email events into Hivemind's dashboard bus for real-time UI updates
    if (options.dashboard !== false) {
      try {
        const { bus } = await import("../dashboard/server.js");
        // Forward email events to dashboard WebSocket bus
        emailMod.emailBus.on("email:seller-alert", (data: unknown) => {
          bus.emit("email:seller-alert", data);
          const d = data as { urgency?: string; summary?: string };
          info(`[Sentinel] Amazon seller alert: ${d.urgency ?? "unknown"} — ${d.summary ?? ""}`);
        });
        emailMod.emailBus.on("email:purchase", (data: unknown) => {
          bus.emit("email:purchase", data);
        });
        emailMod.emailBus.on("email:pipeline-complete", (data: unknown) => {
          bus.emit("email:pipeline-complete", data);
          const d = data as { emails_scanned?: number; emails_flagged?: number; emails_pushed?: number };
          if ((d.emails_flagged ?? 0) > 0) {
            info(`[Email] Pipeline complete: ${d.emails_scanned ?? 0} scanned, ${d.emails_flagged ?? 0} flagged, ${d.emails_pushed ?? 0} pushed`);
          }
        });
      } catch {}
    }

    info("Email module initialized (pipeline scheduler started)");
  } catch (err) {
    warn(`Email module failed to start: ${(err as Error).message}`);
  }

  // ── Initialize Connectors (Discord, Slack, Telegram, Webhooks) ────────────
  let connectorManagerInstance: { disconnectAll(): Promise<void>; getStatuses(): Array<{ name: string; state: string }> } | null = null;
  try {
    const connectorConfigs = parsedConfig["connectors"] as Array<Record<string, unknown>> | undefined;
    if (connectorConfigs && Array.isArray(connectorConfigs) && connectorConfigs.length > 0) {
      s.update("Connecting to external platforms...");
      const { ConnectorManager } = await import("../connectors/connector-manager.js");
      const { trustGate } = await import("../core/trust.js");
      const { submitConnectorTask, setConnectorManager, bus: dashBus } = await import("../dashboard/server.js");

      const cm = new ConnectorManager({
        bus: dashBus,
        trustGate,
        submitTask: async (description: string, taskSource: import("../core/trust.js").TaskSource, _replyContext: import("../connectors/connector-manager.js").ReplyContext) => {
          return await submitConnectorTask(description, taskSource);
        },
      });
      connectorManagerInstance = cm;

      // Make connector statuses available to dashboard REST API
      setConnectorManager(cm);

      await cm.initializeAll(connectorConfigs as any[]);
      const statuses = cm.getStatuses();
      const connectedCount = statuses.filter((st: { state: string }) => st.state === "connected").length;
      if (connectedCount > 0) {
        info(`Connectors: ${connectedCount}/${statuses.length} connected (${statuses.map((st: { name: string; state: string }) => `${st.name}:${st.state}`).join(", ")})`);
      }
    }
  } catch (err) {
    warn(`Connector initialization failed: ${(err as Error).message}`);
  }

  s.succeed("HIVEMIND swarm is running");
  log("");

  if (tandemMode) {
    info("LLM Providers: TANDEM MODE");
    info("  Claude (research/analysis) → Scout, Oracle, Courier");
    info("  Codex o4-mini (code/review) → Builder, Sentinel");
    if (hasGoogle) info("  Gemini (image gen / doc extraction only) → Available");
  } else {
    const providerLabel = llmProvider === "claude-code" ? "Claude Code CLI (Max subscription)"
      : llmProvider === "anthropic" ? "Anthropic API"
      : llmProvider === "openai" ? "OpenAI API"
      : llmProvider === "google" ? "Google Gemini API"
      : llmProvider === "codex" ? "OpenAI Codex CLI (ChatGPT Pro)"
      : llmProvider === "ollama" ? "Ollama (local)"
      : "None (dashboard only)";
    info(`LLM Provider: ${providerLabel}`);
    if (hasGoogle && llmProvider !== "google") info("  Gemini available for image generation & document extraction");
  }
  if (llmProvider === "none") {
    warn("No LLM provider detected. Dashboard is running but agents cannot process tasks.");
    warn("To enable agents, do one of:");
    log("  - Install Claude Code CLI and run: claude login");
    log("  - Install OpenAI Codex CLI: npm i -g @openai/codex && codex auth");
    log("  - Set ANTHROPIC_API_KEY in .env");
    log("  - Set OPENAI_API_KEY in .env");
    log("  - Install Ollama: https://ollama.ai");
  }
  info(`Agents: ${llmAgents.size} active (${agentConfigs.map(a => a.name).join(", ")})`);

  const skillsDir = path.resolve("skills");
  if (fs.existsSync(skillsDir)) {
    const skillCount = fs.readdirSync(skillsDir).filter(e => {
      try { return fs.statSync(path.join(skillsDir, e)).isDirectory(); } catch { return false; }
    }).length;
    info(`Skills: ${skillCount} loaded`);
  }

  info(`Memory: ${path.join(dataDir, "hivemind.db")}${embedder ? " (vector search enabled)" : " (keyword search)"}`);

  if (options.dashboard !== false) {
    info(`Dashboard: http://localhost:${dashboardPort}`);
  }

  log("");
  info('Submit tasks with: hivemind task "your task here"');
  info(`Or POST to: http://localhost:${dashboardPort}/api/tasks`);
  log("");

  if (options.detach) {
    info("Running in detached mode. Use 'hivemind status' to check progress.");
    info("Use 'hivemind down' to stop.");
  } else {
    info("Press Ctrl+C to stop the swarm.");
    await new Promise<void>((resolve) => {
      process.on("SIGINT", () => {
        log("");
        info("Shutting down gracefully...");
        if (connectorManagerInstance) {
          connectorManagerInstance.disconnectAll().catch(() => {});
        }
        resolve();
      });
      process.on("SIGTERM", () => {
        if (connectorManagerInstance) {
          connectorManagerInstance.disconnectAll().catch(() => {});
        }
        resolve();
      });
    });
    success("Swarm stopped.");
  }
}

// ── task ──────────────────────────────────────────────────────────────────────

interface TaskOptions {
  agent?: string;
  json?: boolean;
}

export async function taskCommand(taskDescription: string, options: TaskOptions): Promise<void> {
  // Submit task to running swarm via REST API
  const port = Number(process.env["HIVEMIND_DASHBOARD_PORT"]) || 4000;
  const baseUrl = `http://localhost:${port}`;

  try {
    const response = await fetch(`${baseUrl}/api/tasks`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        description: taskDescription,
        agentId: options.agent,
      }),
      signal: AbortSignal.timeout(300_000), // 5 min timeout for LLM calls
    });

    if (!response.ok) {
      const text = await response.text();
      error(`Failed to submit task: ${text}`);
      process.exit(1);
    }

    const result = await response.json() as Record<string, any>;

    if (options.json) {
      log(JSON.stringify(result, null, 2));
    } else {
      success(`Task completed by ${result["agent"] ?? "agent"}`);
      log("");
      if (result["reasoning"]) {
        info("Reasoning:");
        log(`  ${result["reasoning"]}`);
        log("");
      }
      if (result["output"]) {
        info("Output:");
        log(typeof result["output"] === "string" ? result["output"] : JSON.stringify(result["output"], null, 2));
      }
      if ((result["savedFiles"] as unknown[])?.length) {
        log("");
        success(`Files saved:`);
        for (const f of result["savedFiles"] as string[]) {
          log(`  → ${f}`);
        }
      }
    }
  } catch (err) {
    if (err instanceof TypeError && (err as any).cause?.code === "ECONNREFUSED") {
      error("Swarm is not running. Start it with: hivemind up");
    } else {
      error(err instanceof Error ? err.message : String(err));
    }
    process.exit(1);
  }
}

// ── down ──────────────────────────────────────────────────────────────────────

interface DownOptions {
  force?: boolean;
}

export async function downCommand(options: DownOptions): Promise<void> {
  const s = spinner("Stopping HIVEMIND swarm...");

  if (options.force) {
    s.update("Force stopping all agents...");
    await delay(100);
    s.succeed("All agents terminated.");
  } else {
    s.update("Sending graceful shutdown signal...");
    await delay(200);
    s.update("Waiting for agents to finish current tasks...");
    await delay(200);
    s.succeed("Swarm stopped gracefully.");
  }
}

// ── status ────────────────────────────────────────────────────────────────────

interface StatusOptions {
  json?: boolean;
}

export async function statusCommand(options: StatusOptions): Promise<void> {
  if (!swarmState) {
    info("Swarm is not running. Start it with: hivemind up");
    return;
  }

  const uptimeSeconds = Math.floor(process.uptime());
  const hours = Math.floor(uptimeSeconds / 3600);
  const minutes = Math.floor((uptimeSeconds % 3600) / 60);
  const uptimeStr = hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;

  const agents = Array.from(swarmState.dashboardAgents.values()).map((a: any) => ({
    name: a.name || a.id,
    role: a.type || "agent",
    status: a.status || "idle",
    tasks: a.tasksCompleted || 0,
  }));

  const totalCompleted = agents.reduce((sum, a) => sum + a.tasks, 0);
  const activeCount = agents.filter(a => a.status === "active").length;

  const status = {
    state: activeCount > 0 ? "running" : "idle",
    uptime: uptimeStr,
    agents,
    tasksCompleted: totalCompleted,
    tasksPending: activeCount,
  };

  if (options.json) {
    log(JSON.stringify(status, null, 2));
    return;
  }

  info(`Swarm state: \x1b[32m${status.state}\x1b[0m`);
  info(`Uptime: ${status.uptime}`);
  info(`Tasks: ${status.tasksCompleted} completed, ${status.tasksPending} active`);
  log("");

  table(
    ["Agent", "Role", "Status", "Tasks"],
    status.agents.map((a) => [a.name, a.role, a.status, String(a.tasks)]),
  );
}

// ── skill add ─────────────────────────────────────────────────────────────────

interface SkillAddOptions {
  from?: string;
}

export async function skillAddCommand(
  name: string,
  options: SkillAddOptions,
): Promise<void> {
  const source = options.from ?? "registry";
  const s = spinner(`Installing skill "${name}" from ${source}...`);

  const skillsDir = path.resolve("skills");
  fs.mkdirSync(skillsDir, { recursive: true });
  const targetDir = path.join(skillsDir, name);

  if (fs.existsSync(targetDir)) {
    s.fail(`Skill "${name}" is already installed at ${targetDir}`);
    return;
  }

  try {
    if (source.startsWith("http://") || source.startsWith("https://") || source.startsWith("git@")) {
      // Clone from git URL (use spawn array form to prevent shell injection)
      s.update(`Cloning ${source}...`);
      const { spawnSync } = await import("child_process");
      const result = spawnSync("git", ["clone", "--depth", "1", source, targetDir], { stdio: "pipe" });
      if (result.status !== 0) {
        throw new Error(result.stderr?.toString().trim() || `git clone exited with code ${result.status}`);
      }
    } else if (source !== "registry" && fs.existsSync(source)) {
      // Copy from local path
      s.update(`Copying from ${source}...`);
      fs.cpSync(source, targetDir, { recursive: true });
    } else {
      // Registry: create a skill scaffold (in production, would fetch from registry API)
      s.update(`Fetching "${name}" from registry...`);
      fs.mkdirSync(targetDir, { recursive: true });
      const scaffold = `---\nname: ${name}\nversion: 1.0.0\ndescription: "${name} skill"\nagent: any\ntriggers: ["${name}"]\ntags: ["custom"]\n---\n\n# ${name}\n\nCustom skill. Edit this file to add instructions.\n`;
      fs.writeFileSync(path.join(targetDir, "SKILL.md"), scaffold, "utf-8");
    }
  } catch (err) {
    s.fail(`Failed to install skill "${name}": ${(err as Error).message}`);
    return;
  }

  s.succeed(`Skill "${name}" installed successfully`);
  info(`Skill directory: ${targetDir}/`);

  if (fs.existsSync(path.join(targetDir, "SKILL.md"))) {
    info("SKILL.md found — skill is ready to use.");
  } else {
    warn("No SKILL.md found. Create one to define the skill's behavior.");
  }
}

// ── skill list ────────────────────────────────────────────────────────────────

interface SkillListOptions {
  available?: boolean;
}

export async function skillListCommand(options: SkillListOptions): Promise<void> {
  if (options.available) {
    info("Available skills from the registry:");
    log("");
    table(
      ["Name", "Version", "Description"],
      [
        ["web-search", "1.2.0", "Search the web and extract content"],
        ["code-exec", "1.0.3", "Execute code in sandboxed environments"],
        ["file-manager", "1.1.0", "Read, write, and manage files"],
        ["summarization", "1.0.1", "Summarize long documents and conversations"],
        ["task-planning", "1.3.0", "Break down goals into executable tasks"],
        ["delegation", "1.0.0", "Delegate tasks to other agents"],
        ["memory", "0.9.0", "Long-term memory and retrieval"],
        ["api-caller", "1.0.2", "Make authenticated API calls"],
      ],
    );
    return;
  }

  const skillsDir = path.resolve("skills");
  if (!fs.existsSync(skillsDir)) {
    warn("No skills directory found. Run 'hivemind init' first.");
    return;
  }

  const installed = fs.readdirSync(skillsDir).filter((entry) => {
    return fs.statSync(path.join(skillsDir, entry)).isDirectory();
  });

  if (installed.length === 0) {
    info('No skills installed. Run "hivemind skill add <name>" to install one.');
    return;
  }

  table(
    ["Name", "Status"],
    installed.map((name) => [name, "installed"]),
  );
}

// ── agent spawn ───────────────────────────────────────────────────────────────

interface AgentSpawnOptions {
  name?: string;
  model?: string;
}

export async function agentSpawnCommand(
  role: string,
  options: AgentSpawnOptions,
): Promise<void> {
  const agentName = options.name ?? `${role}-${randomId()}`;
  const model = options.model ?? "default";

  const s = spinner(`Spawning agent "${agentName}" with role "${role}"...`);
  await delay(200);

  s.succeed(`Agent "${agentName}" spawned`);
  info(`Role: ${role}`);
  info(`Model: ${model}`);
  info("The agent is now active in the swarm.");
}

// ── agent list ────────────────────────────────────────────────────────────────

interface AgentListOptions {
  all?: boolean;
}

export async function agentListCommand(options: AgentListOptions): Promise<void> {
  if (!swarmState) {
    info("Swarm is not running. Start it with: hivemind up");
    return;
  }

  const agents = Array.from(swarmState.dashboardAgents.values()).map((a: any) => ({
    name: a.name || a.id,
    role: a.type || "agent",
    status: a.status || "idle",
    pid: process.pid,
  }));

  table(
    ["Name", "Role", "Status", "PID"],
    agents
      .filter((a) => options.all || a.status !== "stopped")
      .map((a) => [a.name, a.role, a.status, String(a.pid)]),
  );
}

// ── config ────────────────────────────────────────────────────────────────────

interface ConfigOptions {
  get?: string;
  set?: string;
  list?: boolean;
}

export async function configCommand(options: ConfigOptions): Promise<void> {
  const configPath = path.resolve("hivemind.yaml");

  if (!fs.existsSync(configPath)) {
    error("No hivemind.yaml found in the current directory.");
    error('Run "hivemind init" to create one.');
    process.exit(1);
  }

  if (options.get) {
    // Simplified key lookup; a real implementation would parse YAML
    info(`${options.get}: (value lookup requires YAML parsing)`);
    return;
  }

  if (options.set) {
    info(`Setting ${options.set}... (requires YAML parsing)`);
    warn("Direct config editing is recommended: edit hivemind.yaml");
    return;
  }

  // Default: show full config
  const content = fs.readFileSync(configPath, "utf-8");
  log(content);
}

// ── skills (pack manager) ─────────────────────────────────────────────────────

export async function packAddCommand(
  gitUrl: string,
  options: { name?: string },
): Promise<void> {
  const { SkillPackManager } = await import("../skills/pack-manager.js");
  const manager = new SkillPackManager();

  const s = spinner(`Installing skill pack from ${gitUrl}...`);

  try {
    const pack = await manager.add(gitUrl, options.name);
    s.succeed(`Pack "${pack.name}" installed`);
    info(`Path: ${pack.localPath}`);
    info(`Skills found: ${pack.skillCount}`);
    if (pack.version) {
      info(`Version: ${pack.version}`);
    }
  } catch (err) {
    s.fail("Install failed");
    error((err as Error).message);
  }
}

export async function packUpdateCommand(packName?: string): Promise<void> {
  const { SkillPackManager } = await import("../skills/pack-manager.js");
  const manager = new SkillPackManager();

  const label = packName ? `Updating pack "${packName}"...` : "Updating all packs...";
  const s = spinner(label);

  try {
    const results = await manager.update(packName);

    if (results.length === 0) {
      s.succeed("No packs installed to update.");
      return;
    }

    s.succeed(`Updated ${results.length} pack${results.length === 1 ? "" : "s"}`);
    log("");

    table(
      ["Pack", "Version", "Skills", "Updated"],
      results.map((p) => [
        p.name,
        p.version ?? "-",
        String(p.skillCount),
        p.updatedAt.slice(0, 10),
      ]),
    );
  } catch (err) {
    s.fail("Update failed");
    error((err as Error).message);
  }
}

export async function packListCommand(): Promise<void> {
  const { SkillPackManager } = await import("../skills/pack-manager.js");
  const manager = new SkillPackManager();

  const packs = manager.list();

  if (packs.length === 0) {
    info("No skill packs installed.");
    info('Run "hivemind skills add <git-url>" to install one.');
    return;
  }

  table(
    ["Pack", "Version", "Skills", "Git URL", "Installed"],
    packs.map((p) => [
      p.name,
      p.version ?? "-",
      String(p.skillCount),
      p.gitUrl,
      p.installedAt.slice(0, 10),
    ]),
  );

  log("");
  info(`Pack directory: ${manager.getBaseDir()}`);
}

export async function packRemoveCommand(packName: string): Promise<void> {
  const { SkillPackManager } = await import("../skills/pack-manager.js");
  const manager = new SkillPackManager();

  const s = spinner(`Removing pack "${packName}"...`);

  try {
    await manager.remove(packName);
    s.succeed(`Pack "${packName}" removed`);
  } catch (err) {
    s.fail("Remove failed");
    error((err as Error).message);
  }
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function randomId(): string {
  return Math.random().toString(36).substring(2, 6);
}
